version: '3.8'

services:
  profile-service-api:
    container_name: profile-service-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5133:5133"
    depends_on:
      - profile-service-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

  profile-service-db:
    container_name: profile-service-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=profileServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/profile-service-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  profile-service-seq:
    image: datalust/seq:latest
    container_name: profile-service-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
     - 5341:5341
     - 8081:80